In [1]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import plotly.express as px
from helper_functions import quick_px_scattermap

In [4]:
station_avg_delay = pd.read_csv("../data/processed/cleaned_delay_data.csv")
station_avg_ridership = pd.read_csv("../data/processed/selected_station_ridership.csv")
sj_adt = pd.read_csv("../data/processed/selected_sj_adt.csv")

station_avg_delay

,pulled_at_utc,trip_id,route_id_x,direction_id,start_date,stop_id,stop_sequence,arr_time,arr_delay_s,dep_time,dep_delay_s,arrival_time,scheduled_arrival_sec,actual_arrival_time,actual_arrival_sec,computed_delay_sec,route_id_y,stop_name
0,2026-03-31T05:24:51.448737,3916424,200,1,20260330,64507,2,1.774936e+09,NaN,1.774936e+09,NaN,22:40:00,81600,2026-03-30 22:40:02-07:00,81602.0,2.0,200,Tasman & 1st
1,2026-03-31T05:24:51.448737,3916424,200,1,20260330,64509,3,1.774936e+09,NaN,NaN,NaN,22:41:15,81675,2026-03-30 22:41:00-07:00,81660.0,-15.0,200,Tasman & Champion
2,2026-03-31T05:24:51.448737,3916424,200,1,20260330,64511,4,1.774936e+09,NaN,NaN,NaN,22:42:57,81777,2026-03-30 22:42:58-07:00,81778.0,1.0,200,Tasman & Calle Del Sol
3,2026-03-31T05:24:51.448737,3916424,200,1,20260330,62694,5,1.774936e+09,NaN,NaN,NaN,22:45:12,81912,2026-03-30 22:45:12-07:00,81912.0,0.0,200,Tasman & Convention Center
4,2026-03-31T05:24:51.448737,3916424,200,1,20260330,62526,6,1.774936e+09,NaN,1.774936e+09,NaN,22:46:00,81960,2026-03-30 22:45:53-07:00,81953.0,-7.0,200,Old Ironsides Station
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3276,2026-03-31T05:24:51.448737,3941625,72,1,20260330,63585,36,1.774939e+09,NaN,NaN,NaN,23:34:58,84898,2026-03-30 23:31:45-07:00,84705.0,-193.0,72,Senter & Buckeye
3277,2026-03-31T05:24:51.448737,3941625,72,1,20260330,63586,37,1.774939e+09,NaN,NaN,NaN,23:36:02,84962,2026-03-30 23:32:34-07:00,84754.0,-208.0,72,Senter & Forestbrook
3278,2026-03-31T05:24:51.448737,3941625,72,1,20260330,63588,38,1.774939e+09,NaN,NaN,NaN,23:36:59,85019,2026-03-30 23:33:09-07:00,84789.0,-230.0,72,Senter & Coyote
3279,2026-03-31T05:24:51.448737,3941625,72,1,20260330,63589,39,1.774939e+09,NaN,NaN,NaN,23:37:44,85064,2026-03-30 23:33:42-07:00,84822.0,-242.0,72,Senter & San Ramon
3280,2026-03-31T05:24:51.448737,3941625,72,1,20260330,63591,40,1.774939e+09,NaN,NaN,NaN,23:39:00,85140,2026-03-30 23:34:26-07:00,84866.0,-274.0,72,Senter & Monterey

In [5]:
station_avg_ridership

,Unnamed: 0,route_name,route_direction_id,stop_id,stop_name,boardings,alightings,total_b_a,geometry
0,0,22,238750,60001,Santa Clara Transit Center,152.880022,110.852250,263.732272,POINT (6144099.62758 1954225.5200159)
1,1,60,239040,60008,San Jose Airport Terminal A,106.410278,97.183657,203.593936,POINT (6146822.45087449 1959780.7825274)
2,2,60,239041,60011,San Jose Airport Terminal B,101.895229,69.917892,171.813122,POINT (6148114.70649208 1958314.71065639)
3,3,60,239041,60014,1st & Metro @ Metro Station,99.060686,57.995466,157.056152,POINT (6150233.01229483 1960218.74228139)
4,4,22,238750,60020,El Camino & Lafayette,40.890986,57.438087,98.329073,POINT (6141651.00288408 1954992.24617273)
...,...,...,...,...,...,...,...,...,...
649,3219,23,238761,66001,San Carlos & Meridian,156.296391,174.049290,330.345680,POINT (6150710.01462166 1943405.86120906)
650,3219,523,238761,66001,San Carlos & Meridian,156.296391,174.049290,330.345680,POINT (6150710.01462166 1943405.86120906)
651,3221,60,239040,66019,San Jose Airport Terminal B,105.515644,69.771954,175.287597,POINT (6148161.17227842 1958273.94794264)
652,3225,25,238790,66033,Clove & Ginger,37.628251,52.159478,89.787729,POINT (6143691.13955183 1939440.16605648)
653,3239,25,238790,66055,Moorpark & Empey,18.094340,27.458611,45.552951,POINT (6143692.33574367 1940729.95317507)

In [6]:
stations_df = pd.merge(station_avg_delay, station_avg_ridership, on='stop_id', how='left')
stations_df

,pulled_at_utc,trip_id,route_id_x,direction_id,start_date,stop_id,stop_sequence,arr_time,arr_delay_s,dep_time,...,route_id_y,stop_name_x,Unnamed: 0,route_name,route_direction_id,stop_name_y,boardings,alightings,total_b_a,geometry
0,2026-03-31T05:24:51.448737,3916424,200,1,20260330,64507,2,1.774936e+09,NaN,1.774936e+09,...,200,Tasman & 1st,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-31T05:24:51.448737,3916424,200,1,20260330,64509,3,1.774936e+09,NaN,NaN,...,200,Tasman & Champion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-03-31T05:24:51.448737,3916424,200,1,20260330,64511,4,1.774936e+09,NaN,NaN,...,200,Tasman & Calle Del Sol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-03-31T05:24:51.448737,3916424,200,1,20260330,62694,5,1.774936e+09,NaN,NaN,...,200,Tasman & Convention Center,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-03-31T05:24:51.448737,3916424,200,1,20260330,62526,6,1.774936e+09,NaN,1.774936e+09,...,200,Old Ironsides Station,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3836,2026-03-31T05:24:51.448737,3941625,72,1,20260330,63585,36,1.774939e+09,NaN,NaN,...,72,Senter & Buckeye,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3837,2026-03-31T05:24:51.448737,3941625,72,1,20260330,63586,37,1.774939e+09,NaN,NaN,...,72,Senter & Forestbrook,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3838,2026-03-31T05:24:51.448737,3941625,72,1,20260330,63588,38,1.774939e+09,NaN,NaN,...,72,Senter & Coyote,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3839,2026-03-31T05:24:51.448737,3941625,72,1,20260330,63589,39,1.774939e+09,NaN,NaN,...,72,Senter & San Ramon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3840,2026-03-31T05:24:51.448737,3941625,72,1,20260330,63591,40,1.774939e+09,NaN,NaN,...,72,Senter & Monterey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN